lab21: general.c stack.c
	gcc -o lab21 general.c stack.c -g 

lab22: main.c calc.c utils.c stack_list.c
	gcc -o lab22 main.c calc.c utils.c stack_list.c -g -lreadline

lab2: main1.c general.c calc.c utils.c stack_list.c stack.c  
	gcc -o lab2  main1.c calc.c utils.c stack_list.c stack.c general.c -g -lreadline
